version: "3.8"
services:
  web:
    build: ./app
    image: 951644293102.dkr.ecr.us-east-1.amazonaws.com/djangomarvelmoviedb:djangomarvelmoviedb_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=MCUDB
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=mcudb.cumjf4fnjqso.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-44-207-237-173.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 951644293102.dkr.ecr.us-east-1.amazonaws.com/djangomarvelmoviedb:djangomarvelmoviedb_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


